[package]
name = "proxy-wasm-http-call"
version = "0.1.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.27", features = ["std"] }
proxy-wasm = "0.2.2"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
